export { solutionsGridConfig } from './solutionsGrid'
export type { SolutionCardConfig, SolutionCardImage } from './solutionsGrid'

export { symptomsConfig } from './symptoms'
export type { SymptomId } from './symptoms'

export { navigationConfig } from './navigation'
export { footerConfig } from './footer'
export { productBannerConfig } from './productBanner'
export { productsHeroConfig } from './productsHero'
export { trustBarConfig } from './trustBar'
export type { TrustBarItemConfig } from './trustBar'
export { productScienceConfig } from './productScience'
export type {
  ProductScienceStepConfig,
  ProductScienceStepTone,
} from './productScience'
export { statHeroConfig } from './statHero'
export { lifestyleConfig } from './lifestyle'
export type { LifestyleCardConfig } from './lifestyle'
export { productJourneyConfig } from './productJourney'
export { reviewsConfig } from './reviews'
export type { ReviewCardConfig } from './reviews'
export { faqConfig } from './faq'
export type { FaqItemConfig } from './faq'

export { journeyConfig } from './journey'
export type { JourneyStepConfig } from './journey'
export { whyChooseConfig } from './whyChoose'
export type { WhyChooseCardConfig } from './whyChoose'
export { manifestoConfig } from './manifesto'
export { reliefIntroConfig } from './reliefIntro'
export { commonColdReliefConfig } from './commonColdRelief'
export { blockedNoseConfig } from './blockedNose'
export { nightCongestionConfig } from './nightCongestion'
export { allergyReliefConfig } from './allergyRelief'
export { kidsCareConfig } from './kidsCare'
export { reliefScienceConfig } from './reliefScience'
export { knowledgeHubConfig } from './knowledgeHub'
export type { KnowledgeHubArticle } from './knowledgeHub'
export { trustedEverywhereConfig } from './trustedEverywhere'
export { aboutHeaderConfig } from './aboutHeader'
export { aboutUsHeroConfig } from './aboutUsHero'
export { aboutUsIntroConfig } from './aboutUsIntro'
export { aboutUsOriginConfig } from './aboutUsOrigin'
export { aboutUsScienceConfig } from './aboutUsScience'
export type { AboutUsScienceStat } from './aboutUsScience'
export { aboutUsPortfolioConfig } from './aboutUsPortfolio'
export type { AboutUsPortfolioItem } from './aboutUsPortfolio'
export { aboutUsManufacturingConfig } from './aboutUsManufacturing'
export type { AboutUsManufacturingItem } from './aboutUsManufacturing'
export { aboutUsImpactConfig } from './aboutUsImpact'
export type { AboutUsImpactStat } from './aboutUsImpact'
export { aboutUsPromiseConfig } from './aboutUsPromise'
export type { AboutUsPromiseCard } from './aboutUsPromise'
export { featuredInsightsConfig } from './featuredInsights'
export type {
  FeaturedInsightArticle,
  FeaturedInsightTopic,
} from './featuredInsights'
export { insightsLibraryConfig } from './insightsLibrary'
export type { InsightsLibraryArticle } from './insightsLibrary'
