import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { aboutUsScienceConfig } from '@configs/aboutUsScience';
/**
 * Figma Section 7 / Science (151:804).
 * Image (151:812): 1344×520, radius 16.
 */
export default function AboutUsScience({ className = '' }) {
    const { index, label, heading, description, image, stats } = aboutUsScienceConfig;
    return (_jsx("section", { className: ['w-full bg-surface-cream', className]
            .filter(Boolean)
            .join(' '), "aria-labelledby": "about-us-science-heading", children: _jsxs("div", { className: "mx-auto flex w-full max-w-page flex-col items-start gap-10 px-4 py-14 sm:gap-12 sm:px-8 sm:py-16 lg:gap-16 lg:px-page-x lg:py-[96px]", children: [_jsxs("header", { className: "flex w-full flex-col items-start justify-between gap-6 lg:flex-row", children: [_jsxs("div", { className: "flex w-full shrink-0 flex-col items-start gap-1.5 lg:w-[140px]", children: [_jsx("p", { className: "text-caption font-semibold leading-[13px] tracking-[1.54px] text-accent-leaf", children: index }), _jsx("p", { className: "text-caption font-semibold leading-[13px] tracking-[1.54px] text-[#9ca3af]", children: label })] }), _jsxs("div", { className: "flex w-full flex-col items-start gap-5 overflow-hidden lg:w-[860px]", children: [_jsx("h2", { id: "about-us-science-heading", className: "w-full max-w-[659px] text-[1.75rem] font-normal leading-[1.3] text-ink sm:text-lead lg:text-heading", children: heading }), _jsx("p", { className: "w-full text-base font-normal leading-[1.75] text-muted-alt", children: description })] })] }), _jsx("div", { className: "relative h-[240px] w-full overflow-hidden rounded-[16px] sm:h-[360px] lg:h-[520px]", children: _jsx("img", { src: image.src, alt: image.alt, width: image.width, height: image.height, className: "absolute inset-0 size-full object-cover object-center", decoding: "async" }) }), _jsx("ul", { className: "flex w-full flex-col gap-px overflow-hidden rounded-[12px] lg:flex-row", children: stats.map((stat) => (_jsxs("li", { className: "flex min-w-0 flex-1 flex-col items-start gap-2 bg-surface-sand p-9", children: [_jsx("p", { className: "text-nav font-medium uppercase leading-normal tracking-[1.68px] text-accent-leaf", children: stat.label }), _jsx("p", { className: "text-[1.75rem] font-medium leading-none text-primary sm:text-heading", children: stat.value }), _jsx("p", { className: "w-full text-body-sm font-normal leading-[1.6] text-muted-alt lg:whitespace-nowrap lg:tracking-[-0.02em]", children: stat.description })] }, stat.id))) })] }) }));
}
