import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { aboutUsImpactConfig } from '@configs/aboutUsImpact';
/**
 * Figma Section 10 / Impact (151:857).
 * Family image (151:881): 932×400, radius 16.
 * Products image (151:887): 400×232, radius 16.
 */
export default function AboutUsImpact({ className = '' }) {
    const { eyebrow, heading, wellbeingEyebrow, family, products, range, stats } = aboutUsImpactConfig;
    return (_jsx("section", { className: ['w-full bg-white', className].filter(Boolean).join(' '), "aria-labelledby": "about-us-impact-heading", children: _jsxs("div", { className: "mx-auto flex w-full max-w-page flex-col items-start gap-10 px-4 py-14 sm:gap-12 sm:px-8 sm:py-16 lg:gap-16 lg:px-page-x lg:pb-[56px] lg:pt-[96px]", children: [_jsxs("header", { className: "flex w-full flex-col items-center gap-5 overflow-hidden text-center", children: [_jsx("p", { className: "text-body-sm font-medium uppercase leading-normal tracking-[1.96px] text-primary", children: eyebrow }), _jsx("h2", { id: "about-us-impact-heading", className: "w-full text-[1.75rem] font-normal leading-[1.3] text-ink sm:text-lead lg:w-[700px] lg:text-heading lg:leading-[1.3]", children: heading })] }), _jsx("ul", { className: "flex w-full flex-col gap-2 lg:flex-row", children: stats.map((stat) => (_jsxs("li", { className: [
                            'flex min-w-0 flex-1 flex-col items-start gap-4 rounded-[16px] p-8 sm:p-12 lg:h-[280px]',
                            stat.backgroundClassName,
                        ].join(' '), children: [_jsx("p", { className: "text-body-sm font-medium uppercase leading-normal text-primary lg:whitespace-nowrap", children: stat.label }), _jsx("p", { className: [
                                    'text-[2.5rem] font-medium leading-none sm:text-[64px]',
                                    stat.valueClassName,
                                ].join(' '), children: stat.value }), _jsx("p", { className: "w-full max-w-[234px] text-base font-normal leading-[1.6] text-muted-alt", children: stat.description })] }, stat.id))) }), _jsxs("div", { className: "flex w-full flex-col items-center gap-3 overflow-hidden", children: [_jsx("p", { className: "text-body-sm font-medium uppercase leading-normal tracking-[1.96px] text-primary", children: wellbeingEyebrow }), _jsxs("div", { className: "flex w-full flex-col items-start gap-3 lg:flex-row", children: [_jsxs("div", { className: "relative h-[240px] w-full min-w-0 overflow-hidden rounded-[16px] sm:h-[320px] lg:h-[400px] lg:flex-1", children: [_jsx("img", { src: family.src, alt: family.alt, width: family.width, height: family.height, className: "absolute inset-0 size-full object-cover object-center", decoding: "async" }), _jsx("div", { className: "relative z-10 flex h-full flex-col items-start justify-end p-5", children: _jsx("span", { className: "rounded-[8px] bg-[rgba(13,31,8,0.33)] px-[14px] py-2.5 text-nav font-semibold leading-normal text-surface-cream", children: family.badge }) })] }), _jsxs("div", { className: "flex w-full flex-col gap-3 overflow-hidden lg:size-[400px] lg:shrink-0", children: [_jsx("div", { className: "relative h-[200px] w-full overflow-hidden rounded-[16px] sm:h-[232px] lg:h-[232px]", children: _jsx("img", { src: products.src, alt: products.alt, width: products.width, height: products.height, className: "absolute inset-0 size-full object-cover object-center", decoding: "async" }) }), _jsxs("div", { className: "flex w-full flex-col items-start gap-2 overflow-hidden rounded-[16px] bg-primary p-6", children: [_jsx("p", { className: "text-nav font-medium leading-normal tracking-[1.68px] text-white", children: range.eyebrow }), _jsx("p", { className: "w-full text-card-title font-medium leading-[1.3] text-surface-cream", children: range.title }), _jsx("p", { className: "w-full text-body-sm font-normal leading-[1.6] text-white", children: range.description })] })] })] })] })] }) }));
}
