import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { aboutUsPortfolioConfig } from '@configs/aboutUsPortfolio';
/**
 * Figma Section 8 / Portfolio (151:827).
 * Product family image (151:835): 1344×480, radius 16.
 */
export default function AboutUsPortfolio({ className = '', }) {
    const { index, label, heading, description, image, items } = aboutUsPortfolioConfig;
    return (_jsx("section", { className: ['w-full bg-surface-warm', className]
            .filter(Boolean)
            .join(' '), "aria-labelledby": "about-us-portfolio-heading", children: _jsxs("div", { className: "mx-auto flex w-full max-w-page flex-col items-start gap-10 px-4 py-14 sm:gap-12 sm:px-8 sm:py-16 lg:gap-16 lg:px-page-x lg:py-[96px]", children: [_jsxs("header", { className: "flex w-full flex-col items-start justify-between gap-6 lg:flex-row", children: [_jsxs("div", { className: "flex w-full shrink-0 flex-col items-start gap-1.5 lg:w-[140px]", children: [_jsx("p", { className: "text-caption font-semibold leading-[13px] tracking-[1.54px] text-accent-leaf", children: index }), _jsx("p", { className: "text-caption font-semibold leading-[13px] tracking-[1.54px] text-[#9ca3af]", children: label })] }), _jsxs("div", { className: "flex w-full flex-col items-start gap-5 overflow-hidden lg:w-[860px]", children: [_jsx("h2", { id: "about-us-portfolio-heading", className: "w-full text-[1.75rem] font-normal leading-[1.3] text-ink sm:text-lead lg:text-heading", children: heading }), _jsx("p", { className: "w-full text-[15px] font-normal leading-[1.7] text-muted-alt", children: description })] })] }), _jsx("div", { className: "relative h-[240px] w-full overflow-hidden rounded-[16px] sm:h-[320px] lg:h-[480px]", children: _jsx("img", { src: image.src, alt: image.alt, width: image.width, height: image.height, className: "absolute inset-0 size-full object-cover object-center", decoding: "async" }) }), _jsx("ul", { className: "flex w-full flex-col gap-2 lg:flex-row", children: items.map((item) => (_jsxs("li", { className: "flex min-w-0 flex-1 flex-col items-start gap-2.5 rounded-[12px] border border-solid border-[rgb(31_79_191_/_0.2)] bg-white p-6", children: [_jsx("p", { className: "text-nav font-normal leading-normal tracking-[1.68px] text-primary", children: item.number }), _jsx("p", { className: "text-base font-medium leading-normal text-primary", children: item.title }), _jsx("p", { className: "w-full text-body-sm font-normal leading-[1.6] text-muted-alt", children: item.description })] }, item.id))) })] }) }));
}
