import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import Button from '@components/Button';
import { commonColdReliefConfig } from '@configs/commonColdRelief';
/** Figma Common cold relief (1:1038) */
export default function CommonColdRelief({ className = '', }) {
    const navigate = useNavigate();
    const { label, heading, description, stats, photography, products, cta, ctaHref, } = commonColdReliefConfig;
    return (_jsx("section", { className: ['w-full bg-[#fafaf8]', className].filter(Boolean).join(' '), "aria-labelledby": "common-cold-heading", children: _jsxs("div", { className: "mx-auto flex w-full max-w-page flex-col items-center gap-10 px-4 py-16 sm:px-8 sm:py-20 lg:flex-row lg:gap-[72px] lg:px-[120px] lg:py-[104px]", children: [_jsx("div", { className: "relative aspect-[600/580] w-full overflow-hidden rounded-[24px] lg:h-[580px] lg:w-[600px] lg:shrink-0 lg:aspect-auto", children: _jsx("img", { src: photography.src, alt: photography.alt, width: photography.width, height: photography.height, className: "absolute inset-0 size-full object-cover", decoding: "async" }) }), _jsxs("div", { className: "flex w-full min-w-0 flex-1 flex-col items-start gap-6 sm:gap-7", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "h-0.5 w-6 shrink-0 bg-primary", "aria-hidden": "true" }), _jsx("span", { className: "text-body-sm font-normal uppercase tracking-[1.96px] text-primary", children: label })] }), _jsx("h2", { id: "common-cold-heading", className: "text-[1.75rem] font-normal leading-[1.3] text-ink sm:text-lead lg:text-heading", children: heading }), _jsx("p", { className: "text-body-sm font-normal leading-[1.4] text-placeholder sm:text-base", children: description }), _jsx("div", { className: "flex w-full items-start border-t border-[#e8e8e0]", children: stats.map((stat, index) => (_jsxs("div", { className: [
                                    'flex flex-col gap-1 pt-6',
                                    index === 0 ? 'pr-6 sm:pr-8' : 'border-l border-[#e8e8e0] pl-6 sm:pl-8',
                                ].join(' '), children: [_jsx("span", { className: "text-[2rem] font-semibold leading-none text-primary sm:text-heading", children: stat.value }), _jsx("span", { className: "text-body-sm font-normal leading-normal text-placeholder", children: stat.label })] }, stat.id))) }), _jsx("div", { className: "relative h-[140px] w-full overflow-hidden rounded-md sm:h-[160px] lg:h-[180px]", children: _jsx("img", { src: products.src, alt: products.alt, width: products.width, height: products.height, className: "absolute inset-0 size-full object-cover", decoding: "async" }) }), _jsx(Button, { type: "button", variant: "secondary", onClick: () => navigate(ctaHref), children: cta })] })] }) }));
}
