import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Fragment } from 'react';
import { useNavigate } from 'react-router-dom';
import ArrowRightIcon from '@icons/ArrowRightIcon';
import { featuredInsightsConfig } from '@configs/featuredInsights';
/** Figma Featured this week (178:2929) */
export default function FeaturedInsights({ className = '', }) {
    const navigate = useNavigate();
    const { ariaLabel, eyebrow, heading, viewAll, viewAllHref, topicsLabel, divider, articles, topics, } = featuredInsightsConfig;
    return (_jsx("section", { className: ['w-full bg-white', className].filter(Boolean).join(' '), "aria-label": ariaLabel, children: _jsxs("div", { className: "mx-auto flex w-full max-w-page flex-col gap-[58px] px-4 py-14 sm:px-8 sm:py-16 lg:px-24 lg:py-20", children: [_jsxs("div", { className: "flex w-full flex-col gap-12 sm:gap-16 lg:gap-[95px]", children: [_jsxs("header", { className: "flex w-full flex-col gap-4 sm:flex-row sm:items-center sm:justify-between sm:gap-6", children: [_jsxs("div", { className: "flex flex-col gap-2.5", children: [_jsx("span", { className: "text-body-sm font-medium uppercase tracking-[1.96px] text-primary", children: eyebrow }), _jsx("h2", { id: "featured-insights-heading", className: "text-[1.75rem] font-normal leading-[1.3] tracking-[0.28px] text-ink-strong", children: heading })] }), _jsxs("button", { type: "button", onClick: () => navigate(viewAllHref), className: "inline-flex shrink-0 cursor-pointer items-center gap-1.5 self-start text-body-sm font-medium text-primary transition-opacity hover:opacity-80 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary sm:self-auto", children: [viewAll, _jsx(ArrowRightIcon, { className: "size-3.5 text-primary" })] })] }), _jsx("div", { className: "flex w-full flex-col gap-10", children: articles.map((article, index) => (_jsxs(Fragment, { children: [_jsxs("article", { className: "flex w-full flex-col items-start gap-8 lg:flex-row lg:gap-[180px]", children: [_jsx("div", { className: "relative h-[200px] w-full shrink-0 overflow-hidden rounded-[20px] sm:h-[240px] lg:h-[240px] lg:w-[500px]", children: _jsx("img", { src: article.image, alt: article.imageAlt, width: article.imageWidth, height: article.imageHeight, className: article.imageFit === 'framed'
                                                        ? 'absolute top-[-71.88%] left-[-3.43%] h-[289.48%] w-[117.45%] max-w-none'
                                                        : 'absolute inset-0 size-full object-cover', decoding: "async" }) }), _jsxs("div", { className: "flex w-full max-w-[568px] flex-col items-start gap-5", children: [_jsx("span", { className: "inline-flex items-center justify-center rounded-[2px] bg-primary px-2 py-1.5 text-body-sm font-medium leading-4 tracking-[0.28px] text-white", children: article.tag }), _jsxs("div", { className: "flex w-full flex-col gap-2.5", children: [_jsx("h3", { className: "text-[1.75rem] font-normal leading-[1.3] tracking-[0.28px] text-ink-strong", children: article.title }), _jsx("p", { className: "text-base font-normal leading-[1.3] text-[#5a6272]", children: article.description })] })] })] }), index < articles.length - 1 ? (_jsx("img", { src: divider, alt: "", width: 1248, height: 1, className: "block h-px w-full max-w-none", decoding: "async", "aria-hidden": "true" })) : null] }, article.id))) })] }), _jsxs("div", { className: "flex w-full flex-col gap-4 border-y border-[#dedcd4] py-5 sm:flex-row sm:items-start sm:justify-between sm:gap-6", children: [_jsx("p", { className: "shrink-0 text-base font-medium text-ink-strong", children: topicsLabel }), _jsx("ul", { className: "flex flex-wrap gap-3", children: topics.map((topic) => (_jsx("li", { children: _jsx("span", { className: "inline-flex items-center rounded-full bg-surface-warm px-[18px] py-2.5 text-body-sm font-normal text-ink-strong", children: topic.label }) }, topic.id))) })] })] }) }));
}
