import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { journeyConfig } from '@configs/journey';
const stepColumns = ['lg:col-start-2', 'lg:col-start-4', 'lg:col-start-6', 'lg:col-start-8'];
/**
 * Homepage clinical timeline (Figma 1:264).
 * Illustration is the cropped timeline art, with the NAM COLD bottle
 * placed over step 3. Step captions sit on the same centers as the circles.
 */
export default function Journey({ badge = journeyConfig.badge, titleBefore = journeyConfig.titleBefore, titleAccent = journeyConfig.titleAccent, titleAfter = journeyConfig.titleAfter, description = journeyConfig.description, steps = journeyConfig.steps, timelineImage = journeyConfig.timelineImage, timelineAlt = journeyConfig.timelineAlt, timelineWidth = journeyConfig.timelineWidth, timelineHeight = journeyConfig.timelineHeight, productImage = journeyConfig.productImage, productWidth = journeyConfig.productWidth, productHeight = journeyConfig.productHeight, glowImage = journeyConfig.glowImage, glowWidth = journeyConfig.glowWidth, glowHeight = journeyConfig.glowHeight, className = '', headingId = 'journey-heading', title, }) {
    return (_jsx("section", { className: ['w-full bg-white pt-14 pb-16 sm:pt-16 lg:pt-[56px] lg:pb-[99px]', className]
            .filter(Boolean)
            .join(' '), "aria-labelledby": headingId, children: _jsxs("div", { className: "mx-auto flex w-full max-w-[1440px] flex-col items-center", children: [_jsxs("header", { className: "flex w-full max-w-[800px] flex-col items-center gap-3 px-4 text-center sm:px-6 lg:px-0", children: [_jsx("span", { className: "px-4 py-1.5 text-body-sm font-normal tracking-[1.68px] text-primary", children: badge }), _jsxs("div", { className: "flex flex-col items-center gap-2", children: [_jsx("h2", { id: headingId, className: "text-[1.75rem] font-normal leading-[1.1] text-ink sm:text-lead lg:text-heading lg:leading-[1.04]", children: title ?? (_jsxs(_Fragment, { children: [titleBefore, _jsx("span", { className: "text-primary", children: titleAccent }), titleAfter] })) }), _jsx("p", { className: "max-w-[800px] text-body-sm font-normal text-[#4b5563] sm:text-base", children: description })] })] }), _jsxs("div", { className: "mt-10 w-full lg:mt-[81px]", children: [_jsx("div", { className: "relative aspect-[1440/220] w-full overflow-hidden", children: _jsxs("div", { className: "absolute inset-x-0 top-0 aspect-[1440/347]", children: [_jsx("div", { className: "absolute top-0 left-[0.208%] h-full w-[99.792%] overflow-hidden", children: _jsx("img", { src: timelineImage, alt: timelineAlt, width: timelineWidth, height: timelineHeight, className: "pointer-events-none absolute top-[-42.07%] left-[-0.04%] h-[142.07%] w-[100.07%] max-w-none", decoding: "async" }) }), _jsx("div", { className: "pointer-events-none absolute top-[8.069%] left-[58.333%] h-[44.957%] w-[10.486%]", children: _jsx("img", { src: glowImage, alt: "", width: glowWidth, height: glowHeight, className: "absolute inset-0 size-full max-w-none", decoding: "async", "aria-hidden": "true" }) }), _jsx("div", { className: "pointer-events-none absolute top-[8.069%] left-[61.181%] h-[43.228%] w-[3.958%] overflow-hidden", children: _jsx("img", { src: productImage, alt: "", width: productWidth, height: productHeight, className: "pointer-events-none absolute top-[-20.03%] left-[-214.97%] h-[132.3%] w-[522.45%] max-w-none", decoding: "async", "aria-hidden": "true" }) })] }) }), _jsx("ul", { className: "mt-8 grid grid-cols-1 gap-6 px-4 sm:grid-cols-2 sm:px-6 lg:mt-[1.806%] lg:grid-cols-[5.833333%_14.166667%_11.388889%_14.166667%_10.555556%_14.166667%_10.555556%_14.166667%_5%] lg:gap-0 lg:px-0", children: steps.map((step, index) => (_jsxs("li", { className: [
                                    'mx-auto flex w-full max-w-[204px] flex-col items-center gap-1.5 text-center',
                                    stepColumns[index],
                                ]
                                    .filter(Boolean)
                                    .join(' '), children: [_jsx("p", { className: "w-full text-card-title font-medium leading-normal text-primary", children: step.title }), _jsx("p", { className: "w-full text-body-sm font-normal leading-normal text-[#4b5563]", children: step.description })] }, step.id))) })] })] }) }));
}
