import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import Button from '@components/Button';
import { kidsCareConfig } from '@configs/kidsCare';
/** Figma Kids care (171:1117) */
export default function KidsCare({ className = '' }) {
    const navigate = useNavigate();
    const { label, heading, description, cta, ctaHref, stats, products, family } = kidsCareConfig;
    return (_jsx("section", { className: ['w-full bg-[#fff8f0]', className].filter(Boolean).join(' '), "aria-labelledby": "kids-care-heading", children: _jsxs("div", { className: "mx-auto flex w-full max-w-page flex-col items-center gap-10 px-4 py-16 sm:px-8 sm:py-20 lg:flex-row lg:gap-[72px] lg:px-[120px] lg:py-[104px]", children: [_jsxs("div", { className: "flex w-full max-w-[520px] shrink-0 flex-col items-start gap-6 sm:gap-7 lg:w-[520px]", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "h-0.5 w-6 shrink-0 bg-accent-rose", "aria-hidden": "true" }), _jsx("span", { className: "text-body-sm font-medium uppercase tracking-[1.96px] text-accent-rose", children: label })] }), _jsx("h2", { id: "kids-care-heading", className: "max-w-[444px] text-[1.75rem] font-normal leading-[1.3] text-ink sm:text-lead lg:text-heading", children: heading }), _jsx("p", { className: "max-w-[491px] text-body-sm font-normal leading-[1.65] text-[#6b4a38] sm:text-base", children: description }), _jsx("div", { className: "flex w-full flex-col gap-4 sm:flex-row", children: stats.map((stat) => (_jsxs("div", { className: "flex min-h-[140px] flex-1 flex-col gap-2 rounded-[14px] border border-[#ffd8c8] bg-white px-4 pt-[29px] pb-4", children: [_jsx("span", { className: "text-2xl font-medium leading-normal whitespace-nowrap text-accent-rose", children: stat.title }), _jsx("span", { className: [
                                            'text-body-sm font-normal leading-[1.4] text-[#6b4a38]',
                                            stat.id === 'newborn-care' ? 'max-w-[190px]' : 'max-w-[171px]',
                                        ].join(' '), children: stat.description })] }, stat.id))) }), _jsx("div", { className: "relative h-[140px] w-full overflow-hidden rounded-[12px]", children: _jsx("img", { src: products.src, alt: products.alt, width: products.width, height: products.height, className: "absolute inset-0 size-full object-cover", decoding: "async" }) }), _jsx(Button, { type: "button", variant: "secondary", className: "bg-accent-rose! shadow-none! hover:bg-accent-rose/90!", onClick: () => navigate(ctaHref), children: cta })] }), _jsx("div", { className: "relative aspect-[608/560] w-full min-w-0 flex-1 overflow-hidden rounded-[24px] lg:h-[560px] lg:aspect-auto", children: _jsx("img", { src: family.src, alt: family.alt, width: family.width, height: family.height, className: "absolute inset-0 size-full object-cover", decoding: "async" }) })] }) }));
}
