import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import Container from '@components/Container';
import ArrowRightIcon from '@icons/ArrowRightIcon';
import { knowledgeHubConfig } from '@configs/knowledgeHub';
/** Figma Knowledge hub (1:780) — article cards match selection */
export default function KnowledgeHub({ className = '' }) {
    const navigate = useNavigate();
    const { eyebrow, heading, viewAll, viewAllHref, readMore, articles } = knowledgeHubConfig;
    return (_jsx("section", { className: ['w-full bg-white', className].filter(Boolean).join(' '), "aria-labelledby": "knowledge-hub-heading", children: _jsxs(Container, { className: "flex flex-col gap-8 py-14 sm:gap-10 sm:py-16 lg:gap-10 lg:py-[88px]", children: [_jsxs("header", { className: "flex w-full flex-col gap-4 sm:gap-6 lg:flex-row lg:items-end lg:justify-between", children: [_jsxs("div", { className: "flex max-w-[700px] flex-col gap-3", children: [_jsx("span", { className: "text-body-sm font-normal uppercase tracking-[1.68px] text-primary", children: eyebrow }), _jsx("h2", { id: "knowledge-hub-heading", className: "max-w-[510px] text-[1.75rem] font-normal leading-[1.3] text-ink sm:text-lead lg:text-heading", children: heading })] }), _jsxs("button", { type: "button", onClick: () => navigate(viewAllHref), className: "inline-flex shrink-0 cursor-pointer items-center gap-1.5 self-start text-button font-normal text-primary transition-opacity hover:opacity-80 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary lg:self-auto", children: [viewAll, _jsx(ArrowRightIcon, { className: "size-3.5 text-primary" })] })] }), _jsx("ul", { className: "grid w-full grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4 lg:gap-5", children: articles.map((article) => (_jsx("li", { className: "h-full", children: _jsxs("article", { className: "flex h-full flex-col overflow-hidden rounded-card border border-border bg-white", children: [_jsx("div", { className: "relative h-[191px] w-full shrink-0 overflow-hidden", children: _jsx("img", { src: article.image, alt: article.imageAlt, width: 318, height: 191, className: "absolute inset-0 size-full object-cover", decoding: "async" }) }), _jsxs("div", { className: "flex flex-1 flex-col items-start gap-3 p-5", children: [_jsx("span", { className: "text-nav font-medium uppercase text-[#a5ce3a]", children: article.tag }), _jsx("h3", { className: "text-base font-medium text-[#111827]", children: article.title }), _jsx("p", { className: "text-label font-normal text-[#4b5563]", children: article.description }), _jsxs("button", { type: "button", className: "mt-auto inline-flex cursor-pointer items-center gap-1 text-nav font-semibold text-primary transition-opacity hover:opacity-80 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary", children: [readMore, _jsx("span", { "aria-hidden": "true", children: "\u2192" })] })] })] }) }, article.id))) })] }) }));
}
