import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { productsHeroConfig } from '@configs/productsHero';
/** Figma Products hero (177:1333) — banner fills a 1442×844 frame */
export default function ProductsHero({ className = '' }) {
    const { badge, heading, ariaLabel, banner, stats } = productsHeroConfig;
    return (_jsx("section", { className: ['relative w-full overflow-hidden bg-white', className]
            .filter(Boolean)
            .join(' '), "aria-label": ariaLabel, children: _jsxs("div", { className: "relative w-full lg:aspect-[1442/844]", children: [_jsx("img", { src: banner.src, alt: banner.alt, width: banner.width, height: banner.height, className: "h-[280px] w-full object-cover object-[72%_center] sm:h-[420px] lg:hidden", decoding: "async", fetchPriority: "high" }), _jsx("div", { className: "pointer-events-none absolute inset-0 hidden overflow-hidden lg:block", "aria-hidden": "true", children: _jsx("div", { className: "absolute top-[-2.844%] left-[-2.843%] h-[102.844%] w-[102.843%] overflow-hidden", children: _jsx("img", { src: banner.src, alt: "", width: banner.width, height: banner.height, className: "absolute top-[-5.36%] left-[-15.04%] h-[105.36%] w-[123.33%] max-w-none", decoding: "async" }) }) }), _jsxs("div", { className: "relative flex w-full max-w-[540px] flex-col items-start gap-6 px-4 py-10 sm:gap-7 sm:px-8 sm:py-12 lg:absolute lg:top-[22.986%] lg:left-[5.548%] lg:w-[37.448%] lg:max-w-none lg:gap-7 lg:p-0", children: [_jsx("span", { className: "rounded-full bg-primary px-3.5 py-[7px] text-caption font-semibold tracking-[1.1px] text-white", children: badge }), _jsx("h1", { className: "text-[1.75rem] font-normal leading-[1.04] tracking-[-0.03em] text-ink sm:text-4xl lg:text-display lg:tracking-[-1.44px]", children: heading }), _jsx("div", { className: "flex items-center gap-6", children: stats.map((stat, index) => (_jsxs("div", { className: "flex items-center gap-6", children: [index > 0 ? (_jsx("div", { className: "h-8 w-px shrink-0 bg-[#e0e5ee]", "aria-hidden": "true" })) : null, _jsxs("div", { className: "flex flex-col gap-0.5 whitespace-nowrap leading-normal", children: [_jsx("span", { className: "text-[22px] font-bold text-[#0a1838]", children: stat.value }), _jsx("span", { className: "text-nav font-normal leading-[1.25] text-[#8a94a6]", children: stat.label })] })] }, stat.id))) })] })] }) }));
}
